version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '03:00'
      timezone: America/New_York
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    ignore:
      - dependency-name: '@stylistic/eslint-plugin'
        versions: ['>=4.0.0']
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      eslint:
        patterns:
          - '*eslint*'
