version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: America/New_York
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    ignore:
      - dependency-name: 'user-agents'
      - dependency-name: 'typescript'
        versions: ['>=5.6.0']
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      typescript and eslint:
        patterns:
          - '*typescript*'
          - '*eslint*'
      jest:
        patterns:
          - '*jest*'
      types:
        patterns:
          - '@types/*'
        exclude-patterns:
          - '*jest*'
